"""Add record_user_id to SharedReport

Revision ID: 1a6acd59f00b
Revises: 575d64c1da85
Create Date: 2025-05-14 16:07:52.627350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6acd59f00b'
down_revision = '575d64c1da85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_report', schema=None) as batch_op:
        batch_op.drop_column('record_user_id')

    # ### end Alembic commands ###
