"""Add calories_burned to DailyRecord

Revision ID: 2e555cbf254f
Revises: 575d64c1da85
Create Date: 2025-05-12 23:29:59.453918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e555cbf254f'
down_revision = '575d64c1da85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_burned', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_record', schema=None) as batch_op:
        batch_op.drop_column('calories_burned')

    # ### end Alembic commands ###
