"""Add total_calories to DailyRecord

Revision ID: 575d64c1da85
Revises: 
Create Date: 2025-05-12 13:43:50.809427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575d64c1da85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_calories', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_record', schema=None) as batch_op:
        batch_op.drop_column('total_calories')

    # ### end Alembic commands ###
