"""Clean migration

Revision ID: 6ed8825a022f
Revises: 1a6acd59f00b
Create Date: 2025-05-15 13:11:39.103478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed8825a022f'
down_revision = '1a6acd59f00b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_burned', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_record', schema=None) as batch_op:
        batch_op.drop_column('calories_burned')

    # ### end Alembic commands ###
