"""Add daily_calorie_needs to DailyRecord

Revision ID: 8036bb7eb74b
Revises: 6ed8825a022f
Create Date: 2025-05-15 15:53:53.228893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8036bb7eb74b'
down_revision = '6ed8825a022f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_calorie_needs', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_record', schema=None) as batch_op:
        batch_op.drop_column('daily_calorie_needs')

    # ### end Alembic commands ###
