"""Add energy_gap to DailyRecord

Revision ID: 952aa4109eb6
Revises: 8036bb7eb74b
Create Date: 2025-05-15 15:59:55.686908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952aa4109eb6'
down_revision = '8036bb7eb74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy_gap', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_record', schema=None) as batch_op:
        batch_op.drop_column('energy_gap')

    # ### end Alembic commands ###
