"""empty message

Revision ID: ebf17ed8b947
Revises: 
Create Date: 2025-05-14 01:21:12.395926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf17ed8b947'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_report', schema=None) as batch_op:
        batch_op.alter_column('report_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
       # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('record_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'daily_record', ['record_id'], ['record_id'])
        batch_op.alter_column('report_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
