"""Add recommended_calories and activity_level to User

Revision ID: ecb5215e6f1a
Revises: 952aa4109eb6
Create Date: 2025-05-15 21:26:36.856745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb5215e6f1a'
down_revision = '952aa4109eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended_calories', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('activity_level', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('activity_level')
        batch_op.drop_column('recommended_calories')

    # ### end Alembic commands ###
